FROM mcr.microsoft.com/mssql/server:2022-latest

ENV ACCEPT_EULA=Y
ENV MSSQL_SA_PASSWORD=Kvcs1857@
ENV MSSQL_TCP_PORT=1433

WORKDIR /src

COPY KoiVet.sql ./KoiVet.sql

RUN (/opt/mssql/bin/sqlservr --accept-eula &) | grep -q "Service Broker manager has started" && /opt/mssql-tools18/bin/sqlcmd -S127.0.0.1 -Usa -PKvcs1857@ -i KoiVet.sql -C

